# build and commit the dist folder after successful CI
name: CI build

on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - 'completed'

jobs:
  on-success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # build dist folder
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release-it --ci

      # commit and push dist folder
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build(packaging): ci build'
          file_pattern: dist build
          add_options: '--force'
