name: 'CI Release'
on:
  workflow_run:
    workflows:
      - 'CI build'
    types:
      - 'completed'
jobs:
# Generate and upload executables to Github releases
  upload-executables:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: ['x64']
        include:
          - os: ubuntu-latest
            arch: 'arm64'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Get latest release tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: 'Store pkg-compliant Windows OS name'
        if: runner.os == 'Windows'
        run: echo "osPkg=win" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: 'Store pkg-compliant Linux and MacOS name'
        if: runner.os != 'Windows'
        run: echo "osPkg=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Figure out binary file name (Windows)
        if: runner.os == 'Windows'
        run: echo "exe=plebbit_${{ env.osPkg }}-${{ matrix.arch }}.exe" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Figure out binary file name (MacOS/Linux)
        if: runner.os != 'Windows'
        run: echo "exe=plebbit_${{ env.osPkg }}-${{ matrix.arch }}" >> $GITHUB_ENV
      - name: Generate ${{ runner.os }}-${{ matrix.arch }} executable
        run: yarn pkg . -t node16-${{ env.osPkg }}-${{ matrix.arch }} -o ${{ env.exe }}

      - name: Upload Binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.exe }}
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true

