name: "CI Release"
on:
  workflow_run:
    workflows:
      - "CI build"
    types:
      - "completed"
jobs:
  # Generate and upload executables to Github releases
  upload-executables-linux-macos:
    name: ${{ matrix.os }}-x64
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Store pkg-compliant Linux and MacOS name
        run: echo "osPkg=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Figure out binary file name
        run: echo "exe=plebbit_${{ env.osPkg }}-x64" >> $GITHUB_ENV

      - name: Generate ${{ runner.os }}-x64 executable
        run: yarn pkg . -t node16-${{ env.osPkg }}-x64 -o ${{ env.exe }}

      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.exe }}
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true

  upload-executables-windows-single-exe:
    name: windows-x64-exe
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate single executable
        run: yarn pkg . -t node16-win-x64 -o plebbit_win-x64.exe
      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: plebbit_win-x64.exe
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true
  upload-executables-windows-installer:
    name: windows-x64-installer
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate installer
        run: yarn oclif pack win
      - name: Rename installer
        shell: bash
        run: find dist/win32/ -name *x64.exe -exec bash -c 'mv $0 plebbit_win-x64_installer.exe' {} \;

      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: plebbit_win-x64_installer.exe
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true

  upload-executables-linux-arm64:
    name: linux-arm64
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: "Get latest release tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          image_additional_mb: 2048
          import_github_env: true
          bind_mount_repository: true
          commands: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&\
            sudo apt-get install -y nodejs gcc g++ make git
            npm install --global yarn
            yarn install --frozen-lockfile
            yarn pkg . -t node16-linux-arm64 -o plebbit_linux-arm64
      - name: Upload Binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: plebbit_linux-arm64
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true
