# CI for the src folder
name: CI

on:
  pull_request:
    branches:
      - master
      - next
    paths:
      - 'test/**'
      - 'src/**'
      - 'config/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches:
      - master
      - next
    paths:
      - 'test/**'
      - 'src/**'
      - 'config/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  test-plebbit-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile
      - run: yarn build

      # disable hosts we shouldn't use
      - run: sudo echo "255.255.255.255 cloudflare-ipfs.com" | sudo tee -a /etc/hosts
      - run: sudo echo "255.255.255.255 pubsubprovider.xyz" | sudo tee -a /etc/hosts

      - run: yarn start:ipfs & sleep 1
      - run: yarn start:api & sleep 1
      
      - run: yarn test:api
      - run: yarn test:cli

